feat: update with env ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -7,15 +7,20 @@ on:
       - feature/setup-terraform
   workflow_dispatch:
 
+env:
+  TARGET_ENV: ${{ github.ref == 'main' && 'prod' || 'dev'}}
+  PROJECT_NAME: "myproject"
+  AWS_region: "eu-central-1"
+
 jobs:
   terraform:
-    name: Infrastructure
+    name: Infrastructure (${{ github.ref == 'main' && 'Prod' || 'Dev'}})
     runs-on: ubuntu-latest
     env:
       TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD}}
     defaults:
       run:
-        working-directory: infra/environments/dev
+        working-directory: infra/environments/${{ github.ref == 'main' && 'prod' || 'dev'}}
   
     steps:
       - name: Checkout code
@@ -41,7 +46,7 @@ jobs:
         run: terraform apply -auto-approve tfplan
   
   deploy:
-    name: Application Deploy
+    name: Application Deploy (${{ github.ref == 'main' && 'Prod' || 'Dev'}})
     needs: terraform
     runs-on: ubuntu-latest
     steps:
@@ -63,19 +68,24 @@ jobs:
       - name: Get Dynamic Bucket Name
         id: find_bucket
         run: |
-          BUCKET_NAME=$(aws resourcegroupstaggingapi get-resources \
-            --tag-filters Key=Project,Values=myproject Key=Environment,Values=dev Key=Type,Values=ArtifactStorage \
-            --resource-type-filters s3 \
-            --query 'ResourceTagMappingList[0].ResourceARN' \
-            --output text | cut -d: -f6)
+          echo "Searching for bucket for ${{ env.TARGET_ENV }}..."
+          for i in {1..6}; do
+            BUCKET_NAME=$(aws resourcegroupstaggingapi get-resources \
+              --tag-filters Key=Project,Values=myproject Key=Environment,Values=dev Key=Type,Values=ArtifactStorage \
+              --resource-type-filters s3 \
+              --query 'ResourceTagMappingList[0].ResourceARN' \
+              --output text | cut -d: -f6)
 
-            if [ -z "$BUCKET_NAME" ] || [ "BUCKET_NAME" == "None"]; then
-              echo "Error: Bucket with specified tags not found."
-              exit 1
+            if [ -z "$BUCKET_NAME" ] || [ "BUCKET_NAME" != "None"]; then
+              cho "Found bucket: $BUCKET_NAME"
+              echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
+              exit 0
             fi
-          
-            echo "Found bucket: $BUCKET_NAME"
-            echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT
+            echo "Waiting for AWS to index tags... (Attempt $i/6)"
+            sleep 20
+          done
+          echo "Error: Bucket not found after 2 minutes."
+          exit 1
 
       - name: Upload to S3
         run: |
@@ -85,11 +95,11 @@ jobs:
         id: find_asg
         run: |
           ASG_NAME=$(aws autoscaling describe-auto-scaling-groups \
-            --query "AutoScalingGroups[?contains(Tags[?Key=='Project'].Value, 'myproject') && contains(Tags[?Key=='Environment'].Value, 'dev')].AutoScalingGroupName" \
+            --query "AutoScalingGroups[?contains(Tags[?Key=='Project'].Value, '${{ env.PROJECT_NAME}}') && contains(Tags[?Key=='Environment'].Value, '${{ env.TARGET_ENV }}')].AutoScalingGroupName" \
             --output text)
 
           if [ -z "$ASG_NAME" ] || [ "$ASG_NAME" == "None" ]; then
-            echo "Error: ASG not found!"
+            echo "Error: ASG for ${{ env.TARGET_ENV }} not found!"
             exit 1
           fi
 
